<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>HandleScope.Setup.Tests</AssemblyName>
    <RootNamespace>HandleScope.Setup.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HandleScope.Setup\HandleScope.Setup.csproj" />
  </ItemGroup>

</Project>
